### ISSUE TITLE
Showing computer's response image

### ISSUE THREAD

**Issue by SebastianJames55** [Ro-yeee/rock-paper-scissors#1]
As a feature to work on in the future, I had a suggestion: the computer's response image could be shown when the player clicks on an image. This would be more interactive.

**Comment by Ro-yeee** [comment]
Ya i thought about that during the build, but at that time i wasnt proficient enough. If i get the time i will definitely add that feature 😄.

**Comment by SebastianJames55** [comment]
Cool, got it. I'll also try.

**Comment by Ro-yeee** [comment]
Sure, you can try it out.
